### ISSUE TITLE
Add "how-to-build" info on README

### ISSUE THREAD

**Issue by filfreire** [petiaccja/Inline-Engine#21]
Add "how-to-build" info on README so any newcomer/contributor can easily clone/fork the project and build locally.

/cc @petiaccja @Yours3lf

**Comment by hsdxpro** [comment]
Hi @filfreire !

Thanks for your kind cc.
I will make that task higher priority, today or tomorrow I will finish it.

**Comment by hsdxpro** [comment]
Done :) Can you check if it fulfills all requirements? I also updated other parts in the README, can you please go through it?

**Comment by filfreire** [comment]
@hsdxpro seems alright. I'm closing this issue.
I'd suggest picking up #22 "Integrate with Continuous Integration"

**Comment by petiaccja** [comment]
Hello,
I recently switched to CMake and updated the build information accordingly. Feel free to take a look!
