### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by filfreire** [petiaccja/Inline-Engine#22]
I recommend automating build process as early as possible.

Once #21 is done, try to make the build process automated on each new commit/pull-request.

There are multiple options, free for Open-source software: [Appveyor](https://www.appveyor.com/) (for Windows programs), [Travis CI](travis-ci.org), [CircleCI](https://circleci.com), etc.

Also add the respective build badge of the CI you choose, usually found on the CI project's settings.

/cc @petiaccja @Yours3lf

**Comment by filfreire** [comment]
BTW, I'd also recommend reading carefully through 

http://www.yegor256.com/2015/06/08/deadly-sins-software-project.html

/cc @petiaccja @Yours3lf

**Comment by petiaccja** [comment]
Hi,
The project has been added to AppVeyor and the badge has been placed on the README.
Thanks for your suggestions!
