### ISSUE TITLE
Create an markdown file of the pipeline document

### ISSUE THREAD

**Issue by filfreire** [petiaccja/Inline-Engine#24]
I'd suggest creating a markdown file of the [pipeline](https://github.com/petiaccja/Inline-Engine/blob/master/Doc/pipeline/desc.pdf) written in English.

Plus update the document's content to the current status.

/cc @petiaccja @Yours3lf @hsdxpro

**Comment by petiaccja** [comment]
I revised and removed those documents, they were badly written drafts for internal communication, providing no value. The purpose of those documents was to explain higher-level concepts about the rendering pipeline, useful for new developers. I will look into uploading our existing documents, which are not perfect descriptions of the current situation but give more insight about the pipeline. I will try to create proper documents, if time allows.

**Comment by filfreire** [comment]
@petiaccja sure thing. Besides, you have the "How to build" section, it's good enough at least for someone who would like to get started.

I'd recommend you have a look at issue #22 and get the project building on a Continuous Integration solution like Appveyor; That way you'd also be able to pick up issues on building the project outside of your own machines.

I also recommend placing some screenshots in the README, under a section for screenshots and maybe youtube video links. Chances of attracting someones attention by displaying images of something actually working are probably higher that just text explaining about the Inline Engine.
