### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Croydon** [petiaccja/Inline-Engine#25]
> There is no licence yet, so the code is 'const' or 'readonly', unavailable for redistribution in any form. We are too lazy to figure out which licence to add, and will not be doing so unless it becomes necessary.

You are literally saying that you don't want to be an open source project. So I have a simple question. Why?

**Comment by hsdxpro** [comment]
We are not stating that, license will be updated soon.

**Comment by hsdxpro** [comment]
The project already open sourced because it's a public repository. Source publicity and license are different terms

**Comment by petiaccja** [comment]
The source code being available does not necesserily mean that it is free ("free" as in GPL). As many game engines do, we may licence it to indie developers and students for free, whereas we charge professionals and studios. An open source licence is not usable for such a model, and until the model is decided (more like until it needs to be decided), the easiest options is to simply deny redistribution of the code.

**Comment by hsdxpro** [comment]
License updated at the bottom of the main page.
